### ISSUE TITLE
A new action temporally blocks the previous action until the selected object is dropped

### ISSUE THREAD

**Issue by quepas** [neu5-przenz-games/the-game#143]
#### The visible behaviour:

When an action occurs, like moving to a player, another action can temporarily block it until the selected object for the action is dropped manually. 

https://user-images.githubusercontent.com/3787206/119730008-8d89c700-be75-11eb-8c92-11f00e66e6b8.mp4

#### The anticipated behaviour:

A new action should entirley cancel and override the previous action.

**Comment by neu5** [comment]
@quepas this should be resolved in #145 
You can check it here: https://the-game-staging.herokuapp.com/
